/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represents the auto-layout configuration for a given view.
*/
export class AutomaticLayout {
    /**
    * The algorithm rank direction.
    */
    'rankDirection'?: AutomaticLayoutRankDirectionEnum;
    /**
    * The separation between ranks (pixels).
    */
    'rankSeparation'?: number;
    /**
    * The separation between nodes in the same rank (pixels).
    */
    'nodeSeparation'?: number;
    /**
    * The separation between edges (pixels).
    */
    'edgeSeparation'?: number;
    /**
    * Whether vertices should be created during automatic layout.
    */
    'vertices'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rankDirection",
            "baseName": "rankDirection",
            "type": "AutomaticLayoutRankDirectionEnum",
            "format": ""
        },
        {
            "name": "rankSeparation",
            "baseName": "rankSeparation",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "nodeSeparation",
            "baseName": "nodeSeparation",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "edgeSeparation",
            "baseName": "edgeSeparation",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "vertices",
            "baseName": "vertices",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutomaticLayout.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AutomaticLayoutRankDirectionEnum {
    TopBottom = 'TopBottom',
    BottomTop = 'BottomTop',
    LeftRight = 'LeftRight',
    RightLeft = 'RightLeft'
}

