/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Documentation } from '../models/Documentation';
import { Relationship } from '../models/Relationship';

/**
* A component (a grouping of related functionality behind an interface that runs inside a container).
*/
export class Component {
    /**
    * The ID of this component in the model.
    */
    'id'?: string;
    /**
    * The name of this component.
    */
    'name'?: string;
    /**
    * A short description of this component.
    */
    'description'?: string;
    /**
    * The technology associated with this component (e.g. Spring Bean).
    */
    'technology'?: string;
    /**
    * A comma separated list of tags associated with this component.
    */
    'tags'?: string;
    /**
    * The URL where more information about this element can be found.
    */
    'url'?: string;
    /**
    * The name of the group in which this component should be included in.
    */
    'group'?: string;
    /**
    * A set of arbitrary name-value properties.
    */
    'properties'?: { [key: string]: any; };
    /**
    * The set of relationships from this component to other elements.
    */
    'relationships'?: Array<Relationship>;
    'documentation'?: Documentation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "technology",
            "baseName": "technology",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<Relationship>",
            "format": ""
        },
        {
            "name": "documentation",
            "baseName": "documentation",
            "type": "Documentation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Component.attributeTypeMap;
    }

    public constructor() {
    }
}

