/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ElementStyle } from '../models/ElementStyle';
import { RelationshipStyle } from '../models/RelationshipStyle';

/**
* The styles associated with this set of views.
*/
export class ConfigurationStyles {
    /**
    * The set of element styles.
    */
    'elements'?: Array<ElementStyle>;
    /**
    * The set of relationship styles.
    */
    'relationships'?: Array<RelationshipStyle>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "elements",
            "baseName": "elements",
            "type": "Array<ElementStyle>",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<RelationshipStyle>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfigurationStyles.attributeTypeMap;
    }

    public constructor() {
    }
}

