/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* A decision record (e.g. architecture decision record).
*/
export class Decision {
    /**
    * The ID of the decision.
    */
    'id'?: string;
    /**
    * The date that the decision was made (ISO 8601 format).
    */
    'date'?: string;
    /**
    * The status of the decision.
    */
    'status'?: DecisionStatusEnum;
    /**
    * The title of the decision.
    */
    'title'?: string;
    /**
    * The Markdown or AsciiDoc content of the section.
    */
    'content'?: string;
    /**
    * The content format type.
    */
    'format'?: DecisionFormatEnum;
    /**
    * The ID of the element (in the model) that this decision applies to (optional).
    */
    'elementId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DecisionStatusEnum",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "DecisionFormatEnum",
            "format": ""
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Decision.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DecisionStatusEnum {
    Proposed = 'Proposed',
    Accepted = 'Accepted',
    Superseded = 'Superseded',
    Deprecated = 'Deprecated',
    Rejected = 'Rejected'
}
export enum DecisionFormatEnum {
    Markdown = 'Markdown',
    AsciiDoc = 'AsciiDoc'
}

