/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContainerInstance } from '../models/ContainerInstance';
import { InfrastructureNode } from '../models/InfrastructureNode';
import { Relationship } from '../models/Relationship';
import { SoftwareSystemInstance } from '../models/SoftwareSystemInstance';

/**
* A deployment node.
*/
export class DeploymentNode {
    /**
    * The ID of this deployment node in the model.
    */
    'id'?: string;
    /**
    * The name of this deployment node.
    */
    'name'?: string;
    /**
    * A short description of this deployment node.
    */
    'description'?: string;
    /**
    * The technology associated with this deployment node (e.g. Apache Tomcat).
    */
    'technology'?: string;
    /**
    * The deployment environment in which this deployment node resides (e.g. \"Development\", \"Live\", etc).
    */
    'environment'?: string;
    /**
    * The number of instances; either a number (e.g. 1, 2, etc) or a range (e.g. 0..N, 0..*, 1..3, etc).
    */
    'instances'?: string;
    /**
    * A comma separated list of tags associated with this deployment node.
    */
    'tags'?: string;
    /**
    * The URL where more information about this element can be found.
    */
    'url'?: string;
    /**
    * The set of child/nested deployment nodes.
    */
    'children'?: Array<DeploymentNode>;
    'infrastructureNodes'?: Array<InfrastructureNode>;
    /**
    * The set of software systems instances running in this deployment node..
    */
    'softwareSystemInstances'?: Array<SoftwareSystemInstance>;
    /**
    * The set of container instances running in this deployment node..
    */
    'containerInstances'?: Array<ContainerInstance>;
    /**
    * A set of arbitrary name-value properties.
    */
    'properties'?: { [key: string]: any; };
    /**
    * The set of relationships from this deployment node to other elements.
    */
    'relationships'?: Array<Relationship>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "technology",
            "baseName": "technology",
            "type": "string",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "instances",
            "baseName": "instances",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<DeploymentNode>",
            "format": ""
        },
        {
            "name": "infrastructureNodes",
            "baseName": "infrastructureNodes",
            "type": "Array<InfrastructureNode>",
            "format": ""
        },
        {
            "name": "softwareSystemInstances",
            "baseName": "softwareSystemInstances",
            "type": "Array<SoftwareSystemInstance>",
            "format": ""
        },
        {
            "name": "containerInstances",
            "baseName": "containerInstances",
            "type": "Array<ContainerInstance>",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<Relationship>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeploymentNode.attributeTypeMap;
    }

    public constructor() {
    }
}

