/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Decision } from '../models/Decision';
import { DocumentationSection } from '../models/DocumentationSection';
import { Image } from '../models/Image';

/**
* A wrapper for documentation.
*/
export class Documentation {
    'sections'?: Array<DocumentationSection>;
    'decisions'?: Array<Decision>;
    'images'?: Array<Image>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<DocumentationSection>",
            "format": ""
        },
        {
            "name": "decisions",
            "baseName": "decisions",
            "type": "Array<Decision>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Image>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Documentation.attributeTypeMap;
    }

    public constructor() {
    }
}

