/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* An instance of a model element (Person, Software System, Container or Component) in a View.
*/
export class ElementView {
    /**
    * The ID of the element.
    */
    'id'?: string;
    /**
    * The horizontal position of the element when rendered.
    */
    'x'?: number;
    /**
    * The vertical position of the element when rendered.
    */
    'y'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "number",
            "format": "integer"
        }    ];

    static getAttributeTypeMap() {
        return ElementView.attributeTypeMap;
    }

    public constructor() {
    }
}

