/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Describes a HTTP based health check.
*/
export class HttpHealthCheck {
    /**
    * The name of the health check.
    */
    'name'?: string;
    /**
    * The health check URL/endpoint.
    */
    'url'?: string;
    /**
    * The polling interval, in seconds.
    */
    'interval'?: number;
    /**
    * The timeout after which a health check is deemed as failed, in milliseconds.
    */
    'timeout'?: number;
    /**
    * A set of name-value pairs corresponding to HTTP headers that should be sent with the request.
    */
    'headers'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number",
            "format": "integer"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HttpHealthCheck.attributeTypeMap;
    }

    public constructor() {
    }
}

