/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Relationship } from '../models/Relationship';

/**
* An infrastructure node.
*/
export class InfrastructureNode {
    /**
    * The ID of this infrastructure node in the model.
    */
    'id'?: string;
    /**
    * The name of this infrastructure node.
    */
    'name'?: string;
    /**
    * A short description of this infrastructure node.
    */
    'description'?: string;
    /**
    * The technology associated with this infrastructure node (e.g. \"Route 53\").
    */
    'technology'?: string;
    /**
    * The deployment environment in which this infrastructure node resides (e.g. \"Development\", \"Live\", etc).
    */
    'environment'?: string;
    /**
    * A comma separated list of tags associated with this infrastructure node.
    */
    'tags'?: string;
    /**
    * The URL where more information about this element can be found.
    */
    'url'?: string;
    /**
    * A set of arbitrary name-value properties.
    */
    'properties'?: { [key: string]: any; };
    /**
    * The set of relationships from this infrastructure node to other elements.
    */
    'relationships'?: Array<Relationship>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "technology",
            "baseName": "technology",
            "type": "string",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<Relationship>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InfrastructureNode.attributeTypeMap;
    }

    public constructor() {
    }
}

