/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeploymentNode } from '../models/DeploymentNode';
import { ModelEnterprise } from '../models/ModelEnterprise';
import { Person } from '../models/Person';
import { SoftwareSystem } from '../models/SoftwareSystem';

/**
* A software architecture model.
*/
export class Model {
    'enterprise'?: ModelEnterprise;
    'people'?: Array<Person>;
    'softwareSystems'?: Array<SoftwareSystem>;
    'deploymentNodes'?: Array<DeploymentNode>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enterprise",
            "baseName": "enterprise",
            "type": "ModelEnterprise",
            "format": ""
        },
        {
            "name": "people",
            "baseName": "people",
            "type": "Array<Person>",
            "format": ""
        },
        {
            "name": "softwareSystems",
            "baseName": "softwareSystems",
            "type": "Array<SoftwareSystem>",
            "format": ""
        },
        {
            "name": "deploymentNodes",
            "baseName": "deploymentNodes",
            "type": "Array<DeploymentNode>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Model.attributeTypeMap;
    }

    public constructor() {
    }
}

