/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Relationship } from '../models/Relationship';

/**
* A person who uses a software system.
*/
export class Person {
    /**
    * The ID of this person in the model.
    */
    'id'?: string;
    /**
    * The name of this person.
    */
    'name'?: string;
    /**
    * A short description of this person.
    */
    'description'?: string;
    /**
    * A comma separated list of tags associated with this person.
    */
    'tags'?: string;
    /**
    * The URL where more information about this element can be found.
    */
    'url'?: string;
    /**
    * The location of this person.
    */
    'location'?: PersonLocationEnum;
    /**
    * The name of the group in which this person should be included in.
    */
    'group'?: string;
    /**
    * A set of arbitrary name-value properties.
    */
    'properties'?: { [key: string]: any; };
    /**
    * The set of relationships from this person to other elements.
    */
    'relationships'?: Array<Relationship>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "PersonLocationEnum",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<Relationship>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Person.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PersonLocationEnum {
    External = 'External',
    Internal = 'Internal',
    Unspecified = 'Unspecified'
}

