/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Represents a user who should have access to a workspace.
*/
export class User {
    /**
    * The username of the user (e.g. e-mail address).
    */
    'username'?: string;
    /**
    * The user\'s role.
    */
    'role'?: UserRoleEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRoleEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserRoleEnum {
    ReadWrite = 'ReadWrite',
    ReadOnly = 'ReadOnly'
}

