/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComponentView } from '../models/ComponentView';
import { Configuration } from '../models/Configuration';
import { ContainerView } from '../models/ContainerView';
import { DeploymentView } from '../models/DeploymentView';
import { DynamicView } from '../models/DynamicView';
import { FilteredView } from '../models/FilteredView';
import { SystemContextView } from '../models/SystemContextView';
import { SystemLandscapeView } from '../models/SystemLandscapeView';

/**
* The set of views onto a software architecture model.
*/
export class Views {
    /**
    * The set of system landscape views.
    */
    'systemLandscapeViews'?: Array<SystemLandscapeView>;
    /**
    * The set of system context views.
    */
    'systemContextViews'?: Array<SystemContextView>;
    /**
    * The set of container views.
    */
    'containerViews'?: Array<ContainerView>;
    /**
    * The set of component views.
    */
    'componentViews'?: Array<ComponentView>;
    /**
    * The set of dynamic views.
    */
    'dynamicViews'?: Array<DynamicView>;
    /**
    * The set of deployment views.
    */
    'deploymentView'?: Array<DeploymentView>;
    /**
    * The set of filtered views.
    */
    'filteredViews'?: Array<FilteredView>;
    'configuration'?: Configuration;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "systemLandscapeViews",
            "baseName": "systemLandscapeViews",
            "type": "Array<SystemLandscapeView>",
            "format": ""
        },
        {
            "name": "systemContextViews",
            "baseName": "systemContextViews",
            "type": "Array<SystemContextView>",
            "format": ""
        },
        {
            "name": "containerViews",
            "baseName": "containerViews",
            "type": "Array<ContainerView>",
            "format": ""
        },
        {
            "name": "componentViews",
            "baseName": "componentViews",
            "type": "Array<ComponentView>",
            "format": ""
        },
        {
            "name": "dynamicViews",
            "baseName": "dynamicViews",
            "type": "Array<DynamicView>",
            "format": ""
        },
        {
            "name": "deploymentView",
            "baseName": "deploymentView",
            "type": "Array<DeploymentView>",
            "format": ""
        },
        {
            "name": "filteredViews",
            "baseName": "filteredViews",
            "type": "Array<FilteredView>",
            "format": ""
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "Configuration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Views.attributeTypeMap;
    }

    public constructor() {
    }
}

