/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Documentation } from '../models/Documentation';
import { Model } from '../models/Model';
import { Views } from '../models/Views';
import { WorkspaceConfiguration } from '../models/WorkspaceConfiguration';

/**
* Represents a Structurizr workspace, which is a wrapper for a software architecture model, views, and documentation.
*/
export class Workspace {
  /**
  * The workspace ID.
  */
  'id'?: number;
  /**
  * The name of the workspace.
  */
  'name'?: string;
  /**
  * A short description of the workspace.
  */
  'description'?: string;
  /**
  * A version number for the workspace.
  */
  'version'?: string;
  /**
  * The thumbnail associated with the workspace; a Base64 encoded PNG file as a data URI (data:image/png;base64).
  */
  'thumbnail'?: string;
  /**
  * The last modified date, in ISO 8601 format (e.g. \"2018-09-08T12:40:03Z\").
  */
  'lastModifiedDate'?: string;
  /**
  * A string identifying the user who last modified the workspace (e.g. an e-mail address or username).
  */
  'lastModifiedUser'?: string;
  /**
  * A string identifying the agent that was last used to modify the workspace (e.g. \"structurizr-java/1.2.0\").
  */
  'lastModifiedAgent'?: string;
  'model'?: Model;
  'views'?: Views;
  'documentation'?: Documentation;
  'configuration'?: WorkspaceConfiguration;
  /**
  * A set of arbitrary name-value properties.
  */
  'properties'?: { [key: string]: any; };

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
    {
      "name": "id",
      "baseName": "id",
      "type": "number",
      "format": "long"
    },
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": ""
    },
    {
      "name": "description",
      "baseName": "description",
      "type": "string",
      "format": ""
    },
    {
      "name": "version",
      "baseName": "version",
      "type": "string",
      "format": ""
    },
    {
      "name": "thumbnail",
      "baseName": "thumbnail",
      "type": "string",
      "format": ""
    },
    {
      "name": "lastModifiedDate",
      "baseName": "lastModifiedDate",
      "type": "string",
      "format": ""
    },
    {
      "name": "lastModifiedUser",
      "baseName": "lastModifiedUser",
      "type": "string",
      "format": ""
    },
    {
      "name": "lastModifiedAgent",
      "baseName": "lastModifiedAgent",
      "type": "string",
      "format": ""
    },
    {
      "name": "model",
      "baseName": "model",
      "type": "Model",
      "format": ""
    },
    {
      "name": "views",
      "baseName": "views",
      "type": "Views",
      "format": ""
    },
    {
      "name": "documentation",
      "baseName": "documentation",
      "type": "Documentation",
      "format": ""
    },
    {
      "name": "configuration",
      "baseName": "configuration",
      "type": "WorkspaceConfiguration",
      "format": ""
    },
    {
      "name": "properties",
      "baseName": "properties",
      "type": "{ [key: string]: any; }",
      "format": ""
    }];

  static getAttributeTypeMap() {
    return Workspace.attributeTypeMap;
  }

  public constructor() {
  }
}

