/**
 * Structurizr
 * The web API for Structurizr.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from '../models/User';

/**
* The workspace configuration (for Structurizr cloud service and on-premises installation).
*/
export class WorkspaceConfiguration {
    'users'?: Array<User>;
    /**
    * The visibility of the workspace
    */
    'visibility'?: WorkspaceConfigurationVisibilityEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<User>",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "WorkspaceConfigurationVisibilityEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkspaceConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkspaceConfigurationVisibilityEnum {
    Public = 'Public',
    Private = 'Private'
}

